name: Build Go Runtime
on:
  push:
    paths: [ 'images/wolfi-go-runtime/**' ]
  repository_dispatch:
    types: [ cve-rebuild-trigger ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  trigger-factory:
    uses: ./.github/workflows/factory-engine.yaml
    with:
      runtime: "go-runtime"
      config_path: "images/wolfi-go-runtime/wolfi-go-runtime.yaml"
      repo_name: "ns-wolfi-go-runtime"
      target_tag: "latest"
      version_cmd: "echo '1.25.9'"
      major_version_cmd: "cut -d. -f1-2"
    secrets: inherit